// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNote(arg1:string):Promise<main.Note>;

export function GetNotes():Promise<Array<main.Note>>;

export function Print(arg1:any):Promise<void>;
